// packages/react-starter/src/components/App.tsx
import { TestInput } from "@workspace/components-react";
import "./App.css";

function App() {
  return (
    <>
      <h1>React Starter</h1>
      <div className="card">
        <p>Hello stencil input</p>
        {/* Fully typed react components auto generated from the stencil component */}
        <TestInput type="number" label="Number" />
        <TestInput disabled label="Disabled" />
        <TestInput type="password" label="Password" />
      </div>
    </>
  );
}

export default App;

// packages/angular-starter/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title: string = "Angular Starter";
}

<main>
  <div>
    <h1 class="scl-font-variant-heading-2">{{ title }}</h1>
    <p>Hello stencil input</p>
    <test-input placeholder="placeholder" type="number" label="Number">
    </test-input>

    <test-input disabled="true" label="Disabled"> </test-input>
    <test-input type="password" label="Password" required> </test-input>
  </div>
</main>
